version: '2.2'
services:
  eloquent:
    build: .
    network_mode: host
    command: sh -c "redis-server --daemonize yes && python3 start.py 0.0.0.0 18081"
    volumes:
      - .:/home/eloquent
    restart: on-failure
    mem_limit: 512m
    mem_reservation: 128m
